-- Lids HD store schema for Supabase.
-- Run this migration once in the Supabase SQL editor or with `supabase db push`.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint primary key,
  handle text not null unique,
  title text not null,
  team text,
  league text,
  category text not null default 'hats',
  silhouette text,
  price numeric(10,2) not null default 0 check (price >= 0),
  images text[] not null default '{}',
  thumbnail text,
  secondary_image text,
  tags text[] not null default '{}',
  badge text,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id text primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null,
  price numeric(10,2) not null default 0 check (price >= 0),
  in_stock boolean not null default false,
  inventory_count integer not null default 0 check (inventory_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(product_id, size)
);

create table if not exists public.drop_calendar (
  id bigint generated by default as identity primary key,
  drop_date date not null,
  drop_time text,
  title text not null,
  teams text,
  description text,
  badge text,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  preferred_size text,
  tier text not null default 'All-Star VIP',
  points integer not null default 0 check (points >= 0),
  joined_year integer not null default extract(year from now())::integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default ('LHD-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))),
  user_id uuid references auth.users(id) on delete set null,
  customer_email text,
  status text not null default 'pending' check (status in ('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled')),
  currency text not null default 'USD',
  subtotal numeric(10,2) not null default 0 check (subtotal >= 0),
  tracking_number text,
  shipping_address jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  variant_id text references public.product_variants(id) on delete set null,
  title text not null,
  size text,
  unit_price numeric(10,2) not null default 0 check (unit_price >= 0),
  quantity integer not null default 1 check (quantity > 0),
  thumbnail text,
  created_at timestamptz not null default now()
);

create table if not exists public.wishlist_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.drop_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  email text,
  drop_title text not null,
  created_at timestamptz not null default now(),
  unique(email, drop_title)
);

create index if not exists products_league_idx on public.products(league);
create index if not exists products_team_idx on public.products(team);
create index if not exists products_active_idx on public.products(is_active);
create index if not exists variants_product_idx on public.product_variants(product_id);
create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists orders_number_idx on public.orders(order_number);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists variants_set_updated_at on public.product_variants;
create trigger variants_set_updated_at before update on public.product_variants
for each row execute function public.set_updated_at();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.drop_calendar enable row level security;
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.drop_notifications enable row level security;

drop policy if exists "Anyone can read active products" on public.products;
create policy "Anyone can read active products" on public.products
for select using (is_active = true);

drop policy if exists "Anyone can read product variants" on public.product_variants;
create policy "Anyone can read product variants" on public.product_variants
for select using (true);

drop policy if exists "Anyone can read drop calendar" on public.drop_calendar;
create policy "Anyone can read drop calendar" on public.drop_calendar
for select using (true);

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles
for select using (auth.uid() = id);

drop policy if exists "Users can create own profile" on public.profiles;
create policy "Users can create own profile" on public.profiles
for insert with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Users can read own orders" on public.orders;
create policy "Users can read own orders" on public.orders
for select using (auth.uid() = user_id or (user_id is null and customer_email = auth.jwt() ->> 'email'));

drop policy if exists "Guests and users can create orders" on public.orders;
create policy "Guests and users can create orders" on public.orders
for insert with check (user_id is null or auth.uid() = user_id);

drop policy if exists "Users can read their order items" on public.order_items;
create policy "Users can read their order items" on public.order_items
for select using (exists (
  select 1 from public.orders o
  where o.id = order_items.order_id
    and (o.user_id = auth.uid() or (o.user_id is null and o.customer_email = auth.jwt() ->> 'email'))
));

drop policy if exists "Guests and users can create order items" on public.order_items;
create policy "Guests and users can create order items" on public.order_items
for insert with check (exists (
  select 1 from public.orders o
  where o.id = order_items.order_id
    and (o.user_id is null or o.user_id = auth.uid())
));

drop policy if exists "Users can manage own wishlist" on public.wishlist_items;
create policy "Users can manage own wishlist" on public.wishlist_items
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Anyone can subscribe to drop notifications" on public.drop_notifications;
create policy "Anyone can subscribe to drop notifications" on public.drop_notifications
for insert with check (email is not null or auth.uid() is not null);

drop policy if exists "Users can read own notifications" on public.drop_notifications;
create policy "Users can read own notifications" on public.drop_notifications
for select using (auth.uid() = user_id or (user_id is null and email = auth.jwt() ->> 'email'));

-- Keep product and variant reads fast for the browser client.
grant select on public.products, public.product_variants, public.drop_calendar to anon, authenticated;
grant select, insert on public.orders, public.order_items, public.drop_notifications to anon, authenticated;
grant select, insert, update, delete on public.profiles, public.wishlist_items to authenticated;
