-- Catalog discovery, editable storefront navigation and protected admin data.
-- This migration is additive: the imported products and existing orders stay intact.

alter table public.profiles add column if not exists role text not null default 'customer';
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('customer', 'admin'));

create index if not exists products_category_active_idx on public.products(category, is_active);
create index if not exists products_group_idx on public.products((metadata->>'source_product_group'));
create index if not exists products_tags_idx on public.products using gin(tags);
create index if not exists products_search_idx on public.products using gin (
  to_tsvector(
    'simple',
    coalesce(title, '') || ' ' || coalesce(handle, '') || ' ' ||
    coalesce(team, '') || ' ' || coalesce(league, '') || ' ' ||
    coalesce(silhouette, '') || ' ' || array_to_string(tags, ' ') || ' ' ||
    coalesce(metadata->>'source_product_group', '') || ' ' ||
    coalesce(metadata->>'source_sku', '')
  )
);

create table if not exists public.store_menus (
  id text primary key,
  name text not null,
  location text not null check (location in ('HEADER', 'FOOTER', 'MOBILE_DRAWER', 'MOBILE_FIXED')),
  status text not null default 'DRAFT' check (status in ('PUBLISHED', 'DRAFT', 'ARCHIVED')),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.store_menu_items (
  id text primary key,
  menu_id text not null references public.store_menus(id) on delete cascade,
  parent_id text references public.store_menu_items(id) on delete cascade,
  label text not null,
  target text not null default '/',
  link_type text not null default 'PAGE' check (link_type in ('PAGE', 'COLLECTION', 'PRODUCT', 'ACTION', 'EXTERNAL')),
  visible boolean not null default true,
  sort_order integer not null default 0,
  image_mode text not null default 'AUTO' check (image_mode in ('AUTO', 'CUSTOM', 'NONE')),
  image_url text not null default '',
  image_alt text not null default '',
  settings jsonb not null default '{}'::jsonb,
  unique(menu_id, parent_id, sort_order)
);

create table if not exists public.store_collections (
  id text primary key,
  handle text not null unique,
  name text not null,
  description text,
  hero text,
  status text not null default 'DRAFT' check (status in ('PUBLISHED', 'DRAFT', 'ARCHIVED')),
  sort_mode text not null default 'NEWEST',
  rules jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.store_collection_products (
  collection_id text not null references public.store_collections(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  position integer not null default 0,
  primary key (collection_id, product_id)
);

create table if not exists public.store_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists store_menu_items_menu_idx on public.store_menu_items(menu_id, parent_id, sort_order);
create index if not exists collection_products_collection_idx on public.store_collection_products(collection_id, position);
create index if not exists admin_audit_entity_idx on public.admin_audit_log(entity_type, entity_id, created_at desc);

create or replace function public.catalog_facets(category_filter text default 'hats')
returns jsonb
language sql
stable
set search_path = public
as $$
  with base as (
    select
      p.id,
      p.league,
      p.team,
      p.silhouette,
      p.tags,
      p.price,
      p.metadata->>'source_product_group' as product_group
    from public.products p
    where p.is_active = true
      and (category_filter is null or p.category = category_filter)
  ),
  league_facets as (
    select league as value, count(*)::integer as count
    from base
    where nullif(trim(league), '') is not null
    group by league
  ),
  team_facets as (
    select team as value, count(*)::integer as count
    from base
    where nullif(trim(team), '') is not null
    group by team
  ),
  group_facets as (
    select product_group as value, count(*)::integer as count
    from base
    where nullif(trim(product_group), '') is not null
    group by product_group
  ),
  silhouette_facets as (
    select silhouette as value, count(*)::integer as count
    from base
    where nullif(trim(silhouette), '') is not null
    group by silhouette
  ),
  tag_facets as (
    select tag as value, count(distinct id)::integer as count
    from base, unnest(base.tags) as tag
    where nullif(trim(tag), '') is not null
    group by tag
  ),
  size_facets as (
    select v.size as value, count(distinct b.id)::integer as count
    from base b
    join public.product_variants v on v.product_id = b.id
    where nullif(trim(v.size), '') is not null
    group by v.size
  )
  select jsonb_build_object(
    'leagues', coalesce((select jsonb_agg(jsonb_build_object('value', value, 'count', count) order by count desc, value) from league_facets), '[]'::jsonb),
    'teams', coalesce((select jsonb_agg(jsonb_build_object('value', value, 'count', count) order by value) from team_facets), '[]'::jsonb),
    'groups', coalesce((select jsonb_agg(jsonb_build_object('value', value, 'count', count) order by value) from group_facets), '[]'::jsonb),
    'silhouettes', coalesce((select jsonb_agg(jsonb_build_object('value', value, 'count', count) order by value) from silhouette_facets), '[]'::jsonb),
    'tags', coalesce((select jsonb_agg(jsonb_build_object('value', value, 'count', count) order by count desc, value) from tag_facets), '[]'::jsonb),
    'sizes', coalesce((select jsonb_agg(jsonb_build_object('value', value, 'count', count) order by value) from size_facets), '[]'::jsonb),
    'minPrice', coalesce((select min(price) from base), 0),
    'maxPrice', coalesce((select max(price) from base), 0)
  );
$$;

grant execute on function public.catalog_facets(text) to anon, authenticated;

create or replace function public.is_store_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role = 'admin' from public.profiles where id = auth.uid()), false);
$$;

revoke all on function public.is_store_admin() from public;
grant execute on function public.is_store_admin() to authenticated;

drop policy if exists "Admins manage products" on public.products;
create policy "Admins manage products" on public.products for all using (public.is_store_admin()) with check (public.is_store_admin());
drop policy if exists "Admins manage product variants" on public.product_variants;
create policy "Admins manage product variants" on public.product_variants for all using (public.is_store_admin()) with check (public.is_store_admin());

drop policy if exists "Admins manage orders" on public.orders;
create policy "Admins manage orders" on public.orders for all using (public.is_store_admin()) with check (public.is_store_admin());
drop policy if exists "Admins read order items" on public.order_items;
create policy "Admins read order items" on public.order_items for select using (public.is_store_admin());
drop policy if exists "Admins manage profiles" on public.profiles;
create policy "Admins manage profiles" on public.profiles for all using (public.is_store_admin()) with check (public.is_store_admin());

alter table public.store_menus enable row level security;
alter table public.store_menu_items enable row level security;
alter table public.store_collections enable row level security;
alter table public.store_collection_products enable row level security;
alter table public.store_settings enable row level security;
alter table public.admin_audit_log enable row level security;

drop policy if exists "Anyone can read published menus" on public.store_menus;
create policy "Anyone can read published menus" on public.store_menus for select using (status = 'PUBLISHED' or public.is_store_admin());
drop policy if exists "Anyone can read visible menu items" on public.store_menu_items;
create policy "Anyone can read visible menu items" on public.store_menu_items for select using (visible = true or public.is_store_admin());
drop policy if exists "Anyone can read published collections" on public.store_collections;
create policy "Anyone can read published collections" on public.store_collections for select using (status = 'PUBLISHED' or public.is_store_admin());
drop policy if exists "Anyone can read published collection products" on public.store_collection_products;
create policy "Anyone can read published collection products" on public.store_collection_products for select using (exists (select 1 from public.store_collections c where c.id = collection_id and (c.status = 'PUBLISHED' or public.is_store_admin())));

drop policy if exists "Admins manage menus" on public.store_menus;
create policy "Admins manage menus" on public.store_menus for all using (public.is_store_admin()) with check (public.is_store_admin());
drop policy if exists "Admins manage menu items" on public.store_menu_items;
create policy "Admins manage menu items" on public.store_menu_items for all using (public.is_store_admin()) with check (public.is_store_admin());
drop policy if exists "Admins manage collections" on public.store_collections;
create policy "Admins manage collections" on public.store_collections for all using (public.is_store_admin()) with check (public.is_store_admin());
drop policy if exists "Admins manage collection products" on public.store_collection_products;
create policy "Admins manage collection products" on public.store_collection_products for all using (public.is_store_admin()) with check (public.is_store_admin());
drop policy if exists "Admins manage settings" on public.store_settings;
create policy "Admins manage settings" on public.store_settings for all using (public.is_store_admin()) with check (public.is_store_admin());
drop policy if exists "Admins read audit log" on public.admin_audit_log;
create policy "Admins read audit log" on public.admin_audit_log for select using (public.is_store_admin());
drop policy if exists "Admins create audit log" on public.admin_audit_log;
create policy "Admins create audit log" on public.admin_audit_log for insert with check (public.is_store_admin());

grant select on public.store_menus, public.store_menu_items, public.store_collections, public.store_collection_products to anon, authenticated;
grant select, insert, update, delete on public.store_menus, public.store_menu_items, public.store_collections, public.store_collection_products, public.store_settings, public.admin_audit_log to authenticated;
grant select, update on public.orders, public.order_items, public.profiles to authenticated;
grant select, insert, update, delete on public.products, public.product_variants to authenticated;
